name: Teldrive Windows

on:
  workflow_dispatch:

jobs:
  run-teldrive:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Extract Teldrive
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-windows-amd64.zip" -OutFile "teldrive.zip"
          Expand-Archive -Path "teldrive.zip" -DestinationPath "."
          if (Test-Path "teldrive-1.7.0-windows-amd64") {
              Rename-Item "teldrive-1.7.0-windows-amd64" "teldrive"
          } elseif (-not (Test-Path "teldrive")) {
              New-Item -ItemType Directory -Path "teldrive" | Out-Null
              Get-ChildItem -Path . -Include teldrive.exe -Recurse | Move-Item -Destination "teldrive"
          }
          Write-Host "✅ Teldrive extracted successfully."

      - name: Create config.toml
        shell: pwsh
        run: |
          New-Item -Path "teldrive\config.toml" -ItemType File -Force | Out-Null
          Add-Content -Path "teldrive\config.toml" "[jwt]"
          Add-Content -Path "teldrive\config.toml" "allowed-users = ['YesBusy']"
          Add-Content -Path "teldrive\config.toml" "secret = '0b3157bc7afa4cfafca0b08a06975a39'"
          Add-Content -Path "teldrive\config.toml" ""
          Add-Content -Path "teldrive\config.toml" "[tg.uploads]"
          Add-Content -Path "teldrive\config.toml" "encryption-key = '.ZEgyoLgJ0UNYMx5wW1wzDaddWIoa2B2'"

      - name: Run Teldrive
        shell: pwsh
        run: |
          cd teldrive
          .\teldrive.exe run --server-port 8080
