name: Teldrive Cloud (Local Mode)

on:
  workflow_dispatch:     # Manual start
  push:
    branches:
      - main

jobs:
  run-teldrive:
    runs-on: ubuntu-latest
    timeout-minutes: 3600   # Run up to 1 hour

    steps:
      - name: Download Teldrive
        run: |
          wget -q https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-linux-amd64.tar.gz
          tar -xzf teldrive-1.7.0-linux-amd64.tar.gz
          chmod +x teldrive-1.7.0-linux-amd64/teldrive

      - name: Run Teldrive locally
        run: |
          ./teldrive-1.7.0-linux-amd64/teldrive --port 8080 &
          sleep 10
          curl -v http://localhost:8080 || true
