name: Run Teldrive (Windows + PostgreSQL)

on:
  workflow_dispatch:

jobs:
  run-teldrive:
    runs-on: windows-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: teldrive
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: teldrive
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U teldrive"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for PostgreSQL to be ready
        shell: pwsh
        run: |
          Write-Host "Waiting for PostgreSQL to be ready..."
          Start-Sleep -Seconds 15

      - name: Download Teldrive
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-windows-amd64.zip" -OutFile "teldrive.zip"

      - name: Extract Teldrive
        shell: pwsh
        run: |
          Expand-Archive -Path "teldrive.zip" -DestinationPath "teldrive"
          Rename-Item -Path "teldrive\teldrive-1.7.0-windows-amd64.exe" -NewName "teldrive.exe"

      - name: Run Teldrive
        shell: pwsh
        run: |
          cd teldrive
          $dataSource = "postgres://teldrive:password123@localhost:5432/teldrive"
          @"
data-source = "$dataSource"
port = 8080
"@ | Out-File -Encoding utf8 config.toml
          Write-Host "✅ Configuration written. Starting Teldrive..."
          ./teldrive.exe --config config.toml
