name: Run Teldrive (Windows + PostgreSQL)

on:
  workflow_dispatch:

jobs:
  run-teldrive:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL
        shell: pwsh
        run: |
          choco install postgresql15 -y
          $env:Path += ";C:\Program Files\PostgreSQL\15\bin"
          Start-Service postgresql
          pg_ctl status

      - name: Setup PostgreSQL Database
        shell: pwsh
        run: |
          $env:Path += ";C:\Program Files\PostgreSQL\15\bin"
          psql -U postgres -c "CREATE DATABASE teldrive;"
          psql -U postgres -c "CREATE USER teldrive WITH PASSWORD 'password123';"
          psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE teldrive TO teldrive;"

      - name: Download and Extract Teldrive
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-windows-amd64.zip" -OutFile "teldrive.zip"
          Expand-Archive -Path "teldrive.zip" -DestinationPath "."
          Rename-Item "teldrive-1.7.0-windows-amd64" "teldrive"

      - name: Create config.toml
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "teldrive" | Out-Null
          @"
          [db]
          data-source = "postgres://teldrive:password123@localhost:5432/teldrive"

          [jwt]
          allowed-users = ["YesBusy"]
          secret = "0b3157bc7afa4cfafca0b08a06975a39"

          [tg.uploads]
          encryption-key = ".ZEgyoLgJ0UNYMx5wW1wzDaddWIoa2B2"
          "@ | Out-File -FilePath "teldrive\config.toml" -Encoding UTF8

      - name: Run Teldrive
        shell: pwsh
        run: |
          cd teldrive
          .\teldrive.exe run --config config.toml
