name: Run Teldrive with Playit Tunnel

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-teldrive:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Teldrive binary
        run: |
          wget -q https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-linux-amd64.tar.gz
          tar -xzf teldrive-1.7.0-linux-amd64.tar.gz
          mv teldrive-1.7.0-linux-amd64 teldrive
          chmod +x teldrive

      - name: Run Teldrive server
        run: |
          nohup ./teldrive serve > server.log 2>&1 &
          sleep 5
          echo "Teldrive server started."

      - name: Download Playit client
        run: |
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
          mv playit-linux-amd64 playit
          chmod +x playit

      - name: Connect Playit tunnel
        env:
          PLAYIT_AUTH: ${{ secrets.PLAYIT_AUTH }}
        run: |
          echo "Connecting Playit tunnel..."
          nohup ./playit --secret "$PLAYIT_AUTH" > playit.log 2>&1 &
          sleep 10
          echo "Playit tunnel started successfully."

      - name: Keep alive
        run: |
          echo "Running... Press Ctrl+C to stop locally."
          tail -f /dev/null
