name: Teldrive Cloud (Fixed Extract)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-teldrive:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Download Teldrive
        run: |
          wget -q https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-linux-amd64.tar.gz
          tar -xzf teldrive-1.7.0-linux-amd64.tar.gz
          chmod +x teldrive

      - name: Run Teldrive locally
        run: |
          ./teldrive --port 8080 &
          sleep 10
          curl -v http://localhost:8080 || true
