name: Teldrive Cloud (Playit + Telegram API)

on:
  workflow_dispatch:

jobs:
  teldrive:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # up to 6 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Teldrive
        run: |
          mkdir -p teldrive
          cd teldrive
          wget -q https://github.com/tgdrive/teldrive/releases/download/1.7.0/teldrive-1.7.0-linux-amd64.tar.gz
          tar -xzf teldrive-1.7.0-linux-amd64.tar.gz
          chmod +x teldrive

      - name: Download Playit
        run: |
          wget -q https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
          chmod +x playit-linux-amd64
          mv playit-linux-amd64 playit

      - name: Run Teldrive + Playit
        env:
          PLAYIT_AUTH: ${{ secrets.PLAYIT_AUTH }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        run: |
          cd teldrive
          nohup ./teldrive --port 8080 \
            --telegram-api-id "$TELEGRAM_API_ID" \
            --telegram-api-hash "$TELEGRAM_API_HASH" &
          cd ..
          nohup ./playit -s "$PLAYIT_AUTH" &
          echo "✅ Teldrive started and connected to Playit tunnel"
          sleep 3600  # 1 hour runtime (can increase)
